# Clustering

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import scipy
from sklearn.neighbors import KNeighborsClassifier

# чтоб картинки рисовались в тетрадке
%matplotlib inline 

In [3]:
data = pd.read_csv('adult_data.csv')
data = data.sample(100, random_state=123)
data.head()

age   workclass   fnlwgt   education   education-num  \
20713   55   State-gov   199713   Bachelors              13   
13495   65     Private   115890   Bachelors              13   
12367   29     Private   145592     HS-grad               9   
22402   53   State-gov   231472   Doctorate              16   
18338   32     Private   107218   Bachelors              13   

            marital-status         occupation    relationship  \
20713   Married-civ-spouse     Prof-specialty         Husband   
13495   Married-civ-spouse   Transport-moving         Husband   
12367        Never-married       Craft-repair   Not-in-family   
22402   Married-civ-spouse     Prof-specialty         Husband   
18338        Never-married       Adm-clerical   Not-in-family   

                      race    sex   capital-gain   capital-loss  \
20713                White   Male              0              0   
13495                White   Male              0              0   
12367                White   Male              0              0   
22402                White   Male              0              0   
18338   Asian-Pac-Islander   Male              0              0   

        hours-per-week  native-country  salary  
20713               15   United-States   <=50K  
13495               20   United-States   <=50K  
12367               40       Guatemala   <=50K  
22402               40   United-States    >50K  
18338               40   United-States   <=50K

In [4]:
avail = [col for col, typ in zip(data.columns, data.dtypes) if '64' in str(typ)]

data = data[avail]

In [5]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import MinMaxScaler

In [6]:
data = pd.DataFrame(MinMaxScaler().fit_transform(data), columns=data.columns)
data

age    fnlwgt   education-num   capital-gain   capital-loss  \
0   0.584615  0.349736        0.800000       0.000000       0.000000   
1   0.738462  0.184314        0.800000       0.000000       0.000000   
2   0.184615  0.242930        0.533333       0.000000       0.000000   
3   0.553846  0.412412        1.000000       0.000000       0.000000   
4   0.230769  0.167200        0.800000       0.000000       0.000000   
..       ...       ...             ...            ...            ...   
95  0.123077  0.393239        0.533333       0.000000       0.000000   
96  0.615385  0.293550        0.400000       0.000000       0.000000   
97  0.230769  0.340435        0.533333       0.000000       0.000000   
98  0.415385  0.285188        0.800000       0.076881       0.000000   
99  0.200000  0.753012        0.533333       0.000000       0.818634   

     hours-per-week  
0          0.125000  
1          0.177083  
2          0.385417  
3          0.385417  
4          0.385417  
..              ...  
95         0.385417  
96         0.385417  
97         0.385417  
98         0.593750  
99         0.125000  

[100 rows x 6 columns]

In [11]:
db = DBSCAN(eps=0.3, min_samples=3)
db.fit_predict(data)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        1, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  1, -1,  0,  0,  0,  0,
        0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
      dtype=int32)

In [12]:
db.components_

array([[0.58461538, 0.34973615, 0.8       , 0.        , 0.        ,
        0.125     ],
       [0.73846154, 0.18431408, 0.8       , 0.        , 0.        ,
        0.17708333],
       [0.18461538, 0.24293005, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.55384615, 0.41241154, 1.        , 0.        , 0.        ,
        0.38541667],
       [0.23076923, 0.16720016, 0.8       , 0.        , 0.        ,
        0.38541667],
       [0.32307692, 0.12084141, 0.53333333, 0.        , 0.        ,
        0.46875   ],
       [0.23076923, 0.46058983, 0.8       , 0.        , 0.        ,
        0.41666667],
       [0.27692308, 0.23282984, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.53846154, 0.14306464, 0.13333333, 0.        , 0.        ,
        0.48958333],
       [0.29230769, 0.30303796, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.13846154, 0.47502575, 0.6       , 0.        , 0.        ,
        0.36458333],
       [0.30769231, 0

In [13]:
pd.DataFrame(db.components_)

0         1         2         3    4         5
0   0.584615  0.349736  0.800000  0.000000  0.0  0.125000
1   0.738462  0.184314  0.800000  0.000000  0.0  0.177083
2   0.184615  0.242930  0.533333  0.000000  0.0  0.385417
3   0.553846  0.412412  1.000000  0.000000  0.0  0.385417
4   0.230769  0.167200  0.800000  0.000000  0.0  0.385417
..       ...       ...       ...       ...  ...       ...
82  0.323077  0.167366  0.600000  0.000000  0.0  0.593750
83  0.123077  0.393239  0.533333  0.000000  0.0  0.385417
84  0.615385  0.293550  0.400000  0.000000  0.0  0.385417
85  0.230769  0.340435  0.533333  0.000000  0.0  0.385417
86  0.415385  0.285188  0.800000  0.076881  0.0  0.593750

[87 rows x 6 columns]

In [18]:
print(db.components_[0])
print(db.components_[1])

[0.58461538 0.34973615 0.8        0.         0.         0.125     ]
[0.73846154 0.18431408 0.8        0.         0.         0.17708333]


In [25]:
from scipy.spatial import distance

In [26]:
distance.pdist(db.components_)

array([0.23183134, 0.55707764, 0.33569598, ..., 0.40976217, 0.49938297,
       0.39693783])

In [27]:
distance.cdist(db.components_, db.components_)

array([[0.        , 0.23183134, 0.55707764, ..., 0.48158127, 0.51402486,
        0.50837264],
       [0.23183134, 0.        , 0.65168649, ..., 0.48008654, 0.62979296,
        0.54228774],
       [0.55707764, 0.65168649, 0.        , ..., 0.45376452, 0.10787692,
        0.41888508],
       ...,
       [0.48158127, 0.48008654, 0.45376452, ..., 0.        , 0.40976217,
        0.49938297],
       [0.51402486, 0.62979296, 0.10787692, ..., 0.40976217, 0.        ,
        0.39693783],
       [0.50837264, 0.54228774, 0.41888508, ..., 0.49938297, 0.39693783,
        0.        ]])

In [28]:
distance.cdist(db.components_, db.components_)[0][1]

0.23183134494871172

In [29]:
distance.euclidean(db.components_[0], db.components_[1])

0.23183134494871172