## Python

### Блок №1  
Исправьте код ниже, чтобы был такой же вывод, как под комментарием

In [1]:
print("I'm a student and I'll become a \"strong\" programmer") #I'm a student and I'll become a "strong" programmer
# Ваш код здесь

print("C:\\Users\\GoodStudent") #C:\Users\GoodStudent
# Ваш код здесь

x = "My name is Agent Smith"
print(x[1]) #y
# Ваш код здесь

print(x[3:16:3]) #nesgt
# Ваш код здесь

I'm a student and I'll become a "strong" programmer
C:\Users\GoodStudent
y
nesgt



### Блок №2

Запрос ввода осуществляется вызовом функции input(). В функцию можно передать строку, которая будет выведена на экран для общения с пользователем, например:

input('Введите ваш возраст')

Ввод пользователя возвращается функцией input в виде строки и может быть присвоен переменной:

age = input('Введите ваш возраст')

Функция input возвращает строку (даже если пользователь ввёл число). Чтобы сконвертировать строку к целому числу, можно сделать следующее:


In [2]:
age_str = input('Введите ваш возраст') # age_str это строка
age = int(age_str) # age это int

Введите ваш возраст3344


Напишите код для следующих 2 задач:

1. Клиент покупает кофе в кафе. За каждые 6 чашек, 1 чашка даётся в качестве бонуса.
Задача: запросить у пользователя кол-во чашек на покупку, вычислить полагающееся кол-во бонусных чашек кофе и вывести это число через print().
# Ваш код здесь

2. Запросить у пользователя координаты x и y двух точек на плоскости. Посчитать расстояние между заданными точками и вывести результат.
Примечание: у каждой точки есть две координаты: x и y. Расстояние рассчитывается по формуле, которую вы с лёгкостью найдёте в Интернете.
# Ваш код здесь

In [4]:
cups_by_buyer = int(input('Number of cups: '))
bonus_cups = cups_by_buyer // 6
print(f'Bonus cups: {bonus_cups}')

Number of cups: 9
Bonus cups: 1


In [5]:
import math

dot1_coords = input('Enter coords of the first dot in form \'x y\':')
dot2_coords = input('Enter coords of the second dot in form \'x y\':')

x1, y1 = dot1_coords.split(' ')
x2, y2 = dot2_coords.split(' ')

x1, x2, y1, y2 = int(x1), int(x2), int(y1), int(y2)

print(math.sqrt((x1 - x2)**2 + (y1 - y2)**2))

Enter coords of the first dot in form 'x y':1 2
Enter coords of the second dot in form 'x y':2 1
1.4142135623730951


### Блок №3 (Numpy)

Импортировать NumPy под именем np

In [6]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [7]:
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [8]:
array_ones = np.ones(10)
print(array_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [9]:
array1 = [x * 2.5 for x in np.ones(10)]
print(array1)

[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [10]:
array2 = np.zeros(10)
array2[4] = 1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Развернуть вектор (первый становится последним)

In [11]:
array3 = np.array([1, 2, 3, 4])
array3 = array3[::-1]
print(array3)

[4 3 2 1]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [12]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [13]:
array = np.array([1, 2, 0, 0, 4, 0])
print(array.nonzero()[0])

[0 1 4]


Создать 3x3 единичную матрицу

In [14]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Создать массив 3x3x3 со случайными значениями

In [15]:
matrix3x3 = np.random.random((3, 3, 3))
print(matrix3x3)

[[[0.61368823 0.40256718 0.80999933]
  [0.19385009 0.91718831 0.94058993]
  [0.27706182 0.79358331 0.49828514]]

 [[0.52771058 0.77028516 0.50941711]
  [0.785396   0.38201678 0.79323067]
  [0.04875259 0.56937825 0.8311522 ]]

 [[0.44383266 0.05498795 0.51220782]
  [0.05020115 0.3476438  0.60999695]
  [0.57236052 0.14331098 0.46340643]]]


Перемножить матрицы 5x3 и 3x2

In [16]:
matrix5x2 = np.random.random((5, 3))
print(matrix5x2, end='\n\n')

matrix3x2 = np.random.random((3, 2))
print(matrix3x2, end='\n\n')

print(matrix5x2 @ matrix3x2)

[[0.87464083 0.13176673 0.34714679]
 [0.63353856 0.61576175 0.35909527]
 [0.385057   0.32418258 0.47097215]
 [0.32194457 0.58057959 0.90064046]
 [0.71104502 0.96947222 0.47314243]]

[[0.69667795 0.59403891]
 [0.07948408 0.28249613]
 [0.6942831  0.73896456]]

[[0.86083448 0.81332345]
 [0.73962938 0.81565555]
 [0.62101607 0.66835089]
 [0.89573797 1.02080047]
 [0.90092179 1.04589605]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [17]:
array = np.linspace(0, 1, 12)[1:-1]
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Заменить максимальный элемент на ноль

In [18]:
array[array.argmax()] = 0
print(array)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.        ]


Преобразовать массив из float в int

In [19]:
array = [int(x) for x in array]
print(array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


Найти наиболее частое значение в массиве

In [20]:
array = [int(x * 10) for x in np.random.random(10)]
print(array)

print(np.bincount(array)) # индекс - число, значение - число повторений
print(np.bincount(array).argmax()) # вернёт индекс, знчание которого наибольшее. т.е. самое частое число

[5, 6, 8, 7, 3, 8, 5, 2, 9, 9]
[0 0 1 1 0 2 1 1 2 2]
5


Найти n наибольших значений в массиве

In [22]:
n = int(input('n: '))
print('Array: ', array)
array.sort()
values = np.unique(array)[::-1]
# print(values)
print(values[0:n])

n: 3
Array:  [5, 6, 8, 7, 3, 8, 5, 2, 9, 9]
[9 8 7]


### Блок №4 (Pandas)

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts). Скачать датасет на свой компьютер и распаковать. Считать csv файл в датафрейм food:

In [1]:
import pandas as pd

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
pd.set_option('precision', 2)

food=pd.read_csv('D:\\DA_practice\\archive\\en.openfoodfacts.org.products.tsv',sep='\t')

c:\users\rc199\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


MemoryError: Unable to allocate 291. MiB for an array with shape (107, 356027) and data type float64

Посмотреть первые 5 записей

In [24]:
food.head()

NameError: name 'food' is not defined

Сколько наблюдений в наборе данных?


In [39]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [40]:
food.shape[1]

163

Напечатайте все названия столбцов

In [41]:
food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [42]:
food.columns[105]

'-fructose_100g'

Какой тип наблюдений в 105 столбце?

In [43]:
food[food.columns[105]].dtype

dtype('float64')

Каково значение имени продукта в 19-м наблюдении?

In [44]:
food.iloc[19,:]['product_name']

'Organic Oat Groats'

### Блок №5 (Pandas - фильтрация данных)

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [3]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')

In [46]:
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [7]:
len(chipo[chipo['item_price'].apply(lambda price: float(price[1:]) >= 10)])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-7-55ebc8aa7af1>, line 1)

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [48]:
chipo.loc[:, ['item_name', 'item_price']]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
...                                     ...        ...
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Сколько было заказано самого дорогого предмета?

In [49]:
prices = [float(price[1:]) for price in chipo['item_price']]

highest_price = prices[np.argmax(prices)]

chipo[chipo['item_price'].apply(lambda price: float(price[1:]) == highest_price)]['quantity']

3598    15
Name: quantity, dtype: int64

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [50]:
sum(chipo[chipo['item_name'].apply(lambda name: name == 'Veggie Salad Bowl')]['quantity'])

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [51]:
len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)])

20